### ISSUE TITLE
Sint wind in APRS

### ISSUE THREAD

**Issue by claudioben** [ToninoTarsi/swpi#22]
Correggere TTLib.py per un corretto aggiornamento dati "umidità" e pioggia in APRS; le correzioni da apportare sono:

# humidity
    if (globalvars.meteo_data.hum_out != None):
        rh = float(globalvars.meteo_data.hum_out / 100 )
        if rh >= 0.995:
            humid_str = "h00"
        else:
#            humid_str = "h" + "%02.0f" % (rh * 100.0)
            humid_str = "h" + "%02.0f" % (globalvars.meteo_data.hum_out)
        send += humid_str

_______________________________________________

# rain last hour -- each count is 0.0204" 
    if (globalvars.meteo_data.rain_rate_1h != None):
        rain_hr_hundredth_inches = float(globalvars.meteo_data.rain_rate_1h * 3.9370078)
        rain_hr_str = "r" + "%03d" % rain_hr_hundredth_inches
#        rain_hr_str = "r" + int(globalvars.meteo_data.rain_rate_1h)
        send += rain_hr_str

    # rain last 24 hours -- each count is 0.0204"
    # so the math accidentally scales perfect -- report in hundreths of inches
    if (globalvars.meteo_data.rain_rate_24h != None) :
        rain_24_hrs_hundredth_inches = float(globalvars.meteo_data.rain_rate_24h * 3.9370078)
        rain_24_hrs_str = "p" + "%03d" % rain_24_hrs_hundredth_inches
#        rain_24_hrs_str = "p" + int(globalvars.meteo_data.rain_rate_24h)
        send += rain_24_hrs_str

 # skip rain since midnight
    if (globalvars.meteo_data.rain_rate != None ) :
        rain_today_hundredth_inches = float(globalvars.meteo_data.rain_rate  * 3.9370078)
        rain_midnight_str = "P" + "%03d" % rain_today_hundredth_inches
        send += rain_midnight_str

**Comment by ToninoTarsi** [comment]
Difficile cosi capire le modifiche .. Prova con un "push request"

**Comment by claudioben** [comment]
Ciao,
scusa la mia ignoranza ma non so cosia sia "push request".

**Comment by claudioben** [comment]
Provo ad elencarti le linee da sostiture nel file TTLib.py:

sostituire la linea:
329        rain_hr_hundredth_inches = int(globalvars.meteo_data.rain_rate_1h  * 0.0393700787)
con la seguente linea:
rain_hr_hundredth_inches = float(globalvars.meteo_data.rain_rate_1h * 3.9370078)

sostituire la linea:
336        rain_24_hrs_hundredth_inches = int(globalvars.meteo_data.rain_rate_24h  * 0.0393700787)
con la seguente linea:
rain_24_hrs_hundredth_inches = float(globalvars.meteo_data.rain_rate_24h * 3.9370078)

sostituire la linea:
342        rain_today_hundredth_inches = int(globalvars.meteo_data.rain_rate  * 0.0393700787)
con la seguente linea:
rain_today_hundredth_inches = float(globalvars.meteo_data.rain_rate  * 3.9370078)

sostituire la linea:
352             humid_str = "h" + "%02.0f" % (rh * 100.0)
con  la seguente linea:
humid_str = "h" + "%02.0f" % (globalvars.meteo_data.hum_out)


Saluti

**Comment by ToninoTarsi** [comment]
Ok fatto .. versione  01.24.95
Al solito aggiorna con "swpi-update"

**Comment by claudioben** [comment]
Grazie Tonino

Claudio
